=== eea/lcp-dataflow/schema/LCP-IED.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
	<xs:element name="LCPQuestionnaire">
		<xs:annotation>
			<xs:documentation>

                XML Schema for Reporting on Combustion Plants under Art 72 of the Industrial Emissions Directive

                Reporting obligation: http://rod.eionet.europa.eu/obligations/756

                The reporting is done through online questionnaire in CDR envelope. The online questionnaire saves the data
                automatically in XML format.

            </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BasicData" type="BasicDataType" minOccurs="1" maxOccurs="1"/>
				<xs:element name="ListOfPlants" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Plant" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PlantName" type="xs:string" minOccurs="1" maxOccurs="1"/>
										<xs:element name="PlantId" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="EPRTRNationalId" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="PlantLocation"  type="PlantLocationType" minOccurs="0" maxOccurs="1"/>
										<xs:element name="GeographicalCoordinate" type="GeographicalCoordinateType" minOccurs="1" maxOccurs="1"/>
										<xs:element name="FacilityName" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="Comments" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="PlantDetails" type="PlantDetailsType" minOccurs="1" maxOccurs="1"/>
										<xs:element name="EnergyInputAndTotalEmissionsToAir" type="EnergyInputAndTotalEmissionsToAirType" minOccurs="1" maxOccurs="1"/>
										<xs:element name="Desulphurisation" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Months" minOccurs="1" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Month" type="MonthType" minOccurs="1" maxOccurs="12"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="UsefulHeat" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="UsefulHeatProportion" type="xs:double" minOccurs="1" maxOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="xml:lang" use="required"/>
		</xs:complexType>
	</xs:element>

	<!--define simple types-->

	<xs:simpleType name="ReferenceYearType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="2016"/>
			<xs:maxInclusive value="2016"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TrueFalseType">
		<xs:annotation>
			<xs:documentation>Checkbox values</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="false"/>
			<xs:enumeration value="true"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateOrNothing">
		<xs:annotation>
			<xs:documentation>Date or null(allows empty xml element)</xs:documentation>
		</xs:annotation>
		<xs:union>
			<xs:simpleType>
				<xs:restriction base='xs:string'>
				  <xs:length value='0'/>
				</xs:restriction>
		  </xs:simpleType>
		  <xs:simpleType>
				<xs:restriction base='xs:date'>
				</xs:restriction>
		  </xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="DoubleOrNothing">
		<xs:annotation>
			<xs:documentation>Double or null(allows empty xml element)</xs:documentation>
		</xs:annotation>
		<xs:union>
			<xs:simpleType>
				<xs:restriction base='xs:string'>
				  <xs:length value='0'/>
				</xs:restriction>
		  </xs:simpleType>
		  <xs:simpleType>
				<xs:restriction base='xs:double'>
				</xs:restriction>
		  </xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="IntOrNothing">
		<xs:annotation>
			<xs:documentation>Integer or null(allows empty xml element)</xs:documentation>
		</xs:annotation>
		<xs:union>
			<xs:simpleType>
				<xs:restriction base='xs:string'>
				  <xs:length value='0'/>
				</xs:restriction>
		  </xs:simpleType>
		  <xs:simpleType>
				<xs:restriction base='xs:integer'>
				</xs:restriction>
		  </xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="BoolorNothing">
		<xs:annotation>
			<xs:documentation>Bool or null(allows empty xml element)</xs:documentation>
		</xs:annotation>
		<xs:union>
			<xs:simpleType>
				<xs:restriction base='xs:string'>
				  <xs:length value='0'/>
				</xs:restriction>
		  </xs:simpleType>
		  <xs:simpleType>
				<xs:restriction base='TrueFalseType'>
				</xs:restriction>
		  </xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="OtherSectorType">
		<xs:annotation>
			<xs:documentation>Other sectors</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="iron_steel">
				<xs:annotation>
					<xs:documentation>Iron/steel</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="esi">
				<xs:annotation>
					<xs:documentation>ESI</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="district_heating">
				<xs:annotation>
					<xs:documentation>District heating</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="chp">
				<xs:annotation>
					<xs:documentation>CHP</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="other">
				<xs:annotation>
					<xs:documentation>Other (non refineries)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="TypeOfCombustionPlantType">
		<xs:annotation>
			<xs:documentation>Type of combustion plant</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Boiler">
				<xs:annotation>
					<xs:documentation>Boiler</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DieselEngine">
				<xs:annotation>
					<xs:documentation>Diesel Engine</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GasEngine">
				<xs:annotation>
					<xs:documentation>Gas Engine</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GasTurbine">
				<xs:annotation>
					<xs:documentation>Gas Turbine</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Others">
				<xs:annotation>
					<xs:documentation>Others</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="DerogationType">
		<xs:annotation>
			<xs:documentation>Derogation value</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Art72.4.b">
				<xs:annotation>
					<xs:documentation>Plant due to additional reporting for operating under an annual average of 1500 hours.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Article31">
				<xs:annotation>
					<xs:documentation>Desulphurisation rate applied in accordance with clauses (1) and (2) of Article 31 of Directive 2010/75/EU</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Article32">
				<xs:annotation>
					<xs:documentation>Exemption from compliance with emission limit values or desulphurisation rates due to coverage by transitional national plan, in accordance with Article 32(2) of Directive 2010/75/EU</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Article33">
				<xs:annotation>
					<xs:documentation>Limited life time derogation granted in accordance with Article 33(1) of Directive 2010/75/EU</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Article34">
				<xs:annotation>
					<xs:documentation>Exemption from compliance with emission limit values and desulphurisation rates due to being a small isolated system, in accordance with Article 34(1) of Directive 2010/75/EU</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Article35">
				<xs:annotation>
					<xs:documentation>District heating plant exempted from compliance with emission limits values and rates of desulphurisation, in accordance with conditions listed in Article 35 of Directive 2010/75/EU</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MonthValueType">
		<xs:annotation>
			<xs:documentation>Month value</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="JAN">
				<xs:annotation>
					<xs:documentation>January</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="FEB">
				<xs:annotation>
					<xs:documentation>February</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="MAR">
				<xs:annotation>
					<xs:documentation>March</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="APR">
				<xs:annotation>
					<xs:documentation>April</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="MAY">
				<xs:annotation>
					<xs:documentation>May</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="JUN">
				<xs:annotation>
					<xs:documentation>June</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="JUL">
				<xs:annotation>
					<xs:documentation>July</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="AUG">
				<xs:annotation>
					<xs:documentation>August</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SEP">
				<xs:annotation>
					<xs:documentation>September</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="OCT">
				<xs:annotation>
					<xs:documentation>October</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NOV">
				<xs:annotation>
					<xs:documentation>November</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DEC">
				<xs:annotation>
					<xs:documentation>December</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OtherSolidFuelsValueType">
		<xs:annotation>
			<xs:documentation>Other Solid Fuel value</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Coke">
				<xs:annotation>
					<xs:documentation>Coke</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Other">
				<xs:annotation>
					<xs:documentation>Other</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="PatentFuels">
				<xs:annotation>
					<xs:documentation>Patent Fuels</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Tar">
				<xs:annotation>
					<xs:documentation>Tar</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OtherGasesValueType">
		<xs:annotation>
			<xs:documentation>Other Gases value</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="BlastFurnaceGas">
				<xs:annotation>
					<xs:documentation>Blast Furnace Gas</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CokeOvenGas">
				<xs:annotation>
					<xs:documentation>Coke Oven Gas</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="FurnaceGas">
				<xs:annotation>
					<xs:documentation>Furnace Gas</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="LPG">
				<xs:annotation>
					<xs:documentation>LPG</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Other">
				<xs:annotation>
					<xs:documentation>Other</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="OxygenSteel">
				<xs:annotation>
					<xs:documentation>Oxygen Steel</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="RefineryGas">
				<xs:annotation>
					<xs:documentation>Refinery Gas</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<!--define complex types-->

	<xs:complexType name="BasicDataType">
		<xs:sequence>
			<xs:element name="MemberState" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ReferenceYear" type="ReferenceYearType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="NumberOfPlants" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Organization" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Address1" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="State" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PostalCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="NameOfDepartmentContactPerson" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Phone" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Email" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PlantLocationType">
		<xs:sequence>
			<xs:element name="City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Region" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PostalCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="CountryCode" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="BuildingNumber" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="StreetName" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MonthType">
		<xs:sequence>
			<xs:element name="MonthValue" type="MonthValueType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="DesulphurisationRate" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SulphurContent" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TechnicalJustification" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PlantDetailsType">
		<xs:sequence>
			<xs:element name="MWth" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="DateOfStartOfOperation" type="DateOrNothing" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Refineries" type="TrueFalseType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="OtherSector" type="OtherSectorType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="OperatingHours" type="IntOrNothing" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Comments" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TypeOfCombustionPlant" type="TypeOfCombustionPlantType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TypeOfCombustionPlantFurtherDetails" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Derogation" type="DerogationType" minOccurs="1" maxOccurs="6"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GeographicalCoordinateType">
		<xs:sequence>
			<xs:element name="Longitude" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="-180"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Latitude" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="-90"/>
						<xs:maxInclusive value="90"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OtherSolidFuelsType">
		<xs:sequence>
			<xs:element name="OtherSolidFuel" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Category" type="OtherSolidFuelsValueType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="Value" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OtherGasesType">
		<xs:sequence>
			<xs:element name="OtherGas" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Category" type="OtherGasesValueType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="Value" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EnergyInputType">
		<xs:sequence>
			<xs:element name="Biomass" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="OtherSolidFuels" type="OtherSolidFuelsType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="LiquidFuels" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="NaturalGas" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="OtherGases" type="OtherGasesType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Coal" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Lignite" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Peat" type="xs:double" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EnergyInputAndTotalEmissionsToAirType">
		<xs:sequence>
			<xs:element name="EnergyInput" type="EnergyInputType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TotalEmissionsToAir" type="TotalEmissionsToAirType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TotalEmissionsToAirType">
		<xs:sequence>
			<xs:element name="SO2" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="NOx" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="TSP" type="xs:double" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== eea/lcp-dataflow/xquery/dummy-test.xml
<LCPQuestionnaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:lang="en"
                  xsi:noNamespaceSchemaLocation="../schema/LCP-IED.xsd">
    <BasicData>
        <MemberState>DE</MemberState>
        <ReferenceYear>2016</ReferenceYear>
        <NumberOfPlants>605</NumberOfPlants>
        <Organization>Umweltbundesamt</Organization>
        <Address1>Wörlitzer Platz 1</Address1>
        <Address2/>
        <City>Dessau-Roßlau</City>
        <State>DE</State>
        <PostalCode>D-06844</PostalCode>
        <NameOfDepartmentContactPerson>Section Emissions Situation</NameOfDepartmentContactPerson>
        <Phone/>
        <Email>LCP@uba.de</Email>
    </BasicData>
    <ListOfPlants>
        <Plant>
            <PlantName>Erdgasverdichter Sayda</PlantName>
            <PlantId>DE0001</PlantId>
            <EPRTRNationalId>14-60-10525170000</EPRTRNationalId>
            <PlantLocation>
                <City>Berlin test</City>
                <Region>region test</Region>
                <PostalCode>test-12345</PostalCode>
                <CountryCode>DE</CountryCode>
                <BuildingNumber>1</BuildingNumber>
                <StreetName>Berlinstrasse test</StreetName>
            </PlantLocation>
            <GeographicalCoordinate>
                <Longitude>13.43958289</Longitude>
                <Latitude>50.70439968</Latitude>
            </GeographicalCoordinate>
            <FacilityName>FacilityName test</FacilityName>
            <Comments>this is a random comment</Comments>
            <PlantDetails>
                <MWth>545</MWth>
                <DateOfStartOfOperation/>
                <Refineries>true</Refineries>
                <OtherSector>iron_steel</OtherSector>
                <OperatingHours>1111</OperatingHours>
                <Comments>not a random comment</Comments>
                <TypeOfCombustionPlant>DieselEngine</TypeOfCombustionPlant>
                <TypeOfCombustionPlantFurtherDetails>FurtherDetail test</TypeOfCombustionPlantFurtherDetails>
                <Derogation>Art72.4.b</Derogation>
            </PlantDetails>
            <EnergyInputAndTotalEmissionsToAir>
                <EnergyInput>
                    <Biomass>3</Biomass>
                    <OtherSolidFuels>
                        <OtherSolidFuel>
                            <Category>Coke</Category>
                            <Value>4</Value>
                        </OtherSolidFuel>
                        <OtherSolidFuel>
                            <Category>Other</Category>
                            <Value>5</Value>
                        </OtherSolidFuel>
                    </OtherSolidFuels>
                    <LiquidFuels>4</LiquidFuels>
                    <NaturalGas>5</NaturalGas>
                    <OtherGases>
                        <OtherGas>
                            <Category>BlastFurnaceGas</Category>
                            <Value>5</Value>
                        </OtherGas>
                        <OtherGas>
                            <Category>LPG</Category>
                            <Value>6</Value>
                        </OtherGas>
                    </OtherGases>
                    <Coal>1</Coal>
                    <Lignite>1</Lignite>
                    <Peat>1</Peat>
                </EnergyInput>
                <TotalEmissionsToAir>
                    <SO2>0.063</SO2>
                    <NOx>21.865</NOx>
                    <TSP>0.009</TSP>
                </TotalEmissionsToAir>
            </EnergyInputAndTotalEmissionsToAir>
            <Desulphurisation>
                <Months>
                    <Month>
                        <MonthValue>JAN</MonthValue>
                        <DesulphurisationRate>78</DesulphurisationRate>
                        <SulphurContent>76</SulphurContent>
                        <TechnicalJustification/>
                    </Month>
                    <Month>
                        <MonthValue>FEB</MonthValue>
                        <DesulphurisationRate>78</DesulphurisationRate>
                        <SulphurContent>76</SulphurContent>
                        <TechnicalJustification/>
                    </Month>
                </Months>
            </Desulphurisation>
            <UsefulHeat>
                <UsefulHeatProportion>67</UsefulHeatProportion>
            </UsefulHeat>
        </Plant>
        <Plant>
            <PlantName>Erdgasverdichter Sayda</PlantName>
            <PlantId>DE0001</PlantId>
            <EPRTRNationalId>14-60-10525170000</EPRTRNationalId>
            <PlantLocation>
                <City>Berlin test</City>
                <Region>region test</Region>
                <PostalCode>test-12345</PostalCode>
                <CountryCode>DE</CountryCode>
                <BuildingNumber>1</BuildingNumber>
                <StreetName>Berlinstrasse test</StreetName>
            </PlantLocation>
            <GeographicalCoordinate>
                <Longitude>13.43958289</Longitude>
                <Latitude>50.70439968</Latitude>
            </GeographicalCoordinate>
            <FacilityName>FacilityName test</FacilityName>
            <Comments>this is a random comment</Comments>
            <PlantDetails>
                <MWth>545</MWth>
                <DateOfStartOfOperation/>
                <Refineries>true</Refineries>
                <OtherSector>iron_steel</OtherSector>
                <OperatingHours>1111</OperatingHours>
                <Comments>not a random comment</Comments>
                <TypeOfCombustionPlant>DieselEngine</TypeOfCombustionPlant>
                <TypeOfCombustionPlantFurtherDetails>FurtherDetail test</TypeOfCombustionPlantFurtherDetails>
                <Derogation>Art72.4.b</Derogation>
            </PlantDetails>
            <EnergyInputAndTotalEmissionsToAir>
                <EnergyInput>
                    <Biomass>3</Biomass>
                    <OtherSolidFuels>
                        <OtherSolidFuel>
                            <Category>Coke</Category>
                            <Value>4</Value>
                        </OtherSolidFuel>
                        <OtherSolidFuel>
                            <Category>Other</Category>
                            <Value>5</Value>
                        </OtherSolidFuel>
                    </OtherSolidFuels>
                    <LiquidFuels>4</LiquidFuels>
                    <NaturalGas>5</NaturalGas>
                    <OtherGases>
                        <OtherGas>
                            <Category>BlastFurnaceGas</Category>
                            <Value>5</Value>
                        </OtherGas>
                        <OtherGas>
                            <Category>LPG</Category>
                            <Value>6</Value>
                        </OtherGas>
                    </OtherGases>
                    <Coal>1</Coal>
                    <Lignite>1</Lignite>
                    <Peat>1</Peat>
                </EnergyInput>
                <TotalEmissionsToAir>
                    <SO2>0.063</SO2>
                    <NOx>21.865</NOx>
                    <TSP>0.009</TSP>
                </TotalEmissionsToAir>
            </EnergyInputAndTotalEmissionsToAir>
            <Desulphurisation>
                <Months>
                    <Month>
                        <MonthValue>JAN</MonthValue>
                        <DesulphurisationRate>78</DesulphurisationRate>
                        <SulphurContent>76</SulphurContent>
                        <TechnicalJustification/>
                    </Month>
                    <Month>
                        <MonthValue>FEB</MonthValue>
                        <DesulphurisationRate>78</DesulphurisationRate>
                        <SulphurContent>76</SulphurContent>
                        <TechnicalJustification/>
                    </Month>
                </Months>
            </Desulphurisation>
            <UsefulHeat>
                <UsefulHeatProportion>67</UsefulHeatProportion>
            </UsefulHeat>
        </Plant>
    </ListOfPlants>
</LCPQuestionnaire>
